version: "2"

linters:
  default: standard
  disable:
    - depguard
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - errcheck
        source: "\\.Unlock\\(\\)"
