"""Multi-task orchestration built on flywheel.

Flywheel core owns the lifecycle of a single task. This package is the layer
above it: deciding *which* task runs next (selection over a prerequisite DAG),
coordinating *several workers* over a shared store (claims + leases), managing
the on-disk task queue / phases, and driving each chosen task through
``flywheel.run_task``. It depends on ``flywheel-core`` and never the other
way around. Library only: verbs are surfaced through the unified product
shell (``flywheel``), and module-level plumbing remains runnable as
``python -m flywheel_orchestrator._workflow``.
"""

from typing import TYPE_CHECKING

from flywheel_orchestrator._autopilot import (
    AUTOPILOT_PHASE,
    DEFAULT_AUTHORING_MAX_TURNS,
    DEFAULT_DISCOVERY_MAX_TURNS,
    DEFAULT_LANDING,
    DEFAULT_TARGET_DEPTH,
    DEFAULT_WEIGHTS,
    GRADER_SOURCE_HELD_OUT,
    GRADER_SOURCE_REPO_COMMAND,
    INTERRUPT_BASE,
    PREEMPTIVE_MAX_TIER,
    TIER_DESCRIPTIONS,
    TIER_WEIGHTS,
    AuthoringResult,
    AutopilotInvoker,
    AutopilotPassResult,
    DiscoveryCollection,
    DiscoverySessionRunner,
    DroppedFinding,
    EmittedTask,
    Finding,
    ScoreBreakdown,
    ScoredFinding,
    ScoreWeights,
    Tier,
    TierVerdict,
    author_finding,
    author_findings,
    authoring_prompt,
    build_repo_invoker,
    build_single_session_options,
    build_single_session_runner,
    build_tier_agents,
    collect_tier_verdicts,
    discover_tier,
    emit_emitted_task,
    orchestrator_prompt,
    parse_tier_verdict,
    recompute_final,
    run_discovery,
    run_refill_pass,
    run_single_session_discovery,
    score_finding,
    select_findings,
    sequence_findings,
    tier_agent_key,
    tier_prompt,
)
from flywheel_orchestrator._claims import (
    EVENT_ACQUIRED,
    EVENT_EXPIRED,
    EVENT_RELEASED,
    EVENT_RENEWED,
    EVENT_STOLEN,
    HUMAN_REVIEW_QUEUE_REASONS,
    ORCHESTRATOR_EVENT_TYPES,
    ORCHESTRATOR_STOP_EVENT_KINDS,
    REASON_ABORTED,
    REASON_AWAITING_APPROVAL,
    REASON_BUDGET_CEILING,
    REASON_NO_PROGRESS,
    REASON_PREREQUISITE_MISSING,
    REASON_RETRIES_EXHAUSTED_AFTER_ESCALATION,
    ClaimLostError,
    ClaimStore,
    GraphSnapshotItem,
    GraphSnapshotRecord,
    HumanReviewQueueEntry,
    InMemoryClaimStore,
    OrchestratorEventRecord,
    OrchestratorStopEventRecord,
    SourceSyncRecord,
    SqliteClaimStore,
    TaskClaim,
    WorkItemRecord,
)
from flywheel_orchestrator._orchestrate import (
    DEFAULT_ESCALATION_BOUND,
    DEFAULT_LANDING_REDRIVE_BOUND,
    DEFAULT_LEASE_SECONDS,
    DEFAULT_PREREQ_REDRIVE_BOUND,
    DEFAULT_RECONCILE_SECONDS,
    DEFAULT_SWEEP_SECONDS,
    EscalationDriver,
    EscalationOutcome,
    EscalationRequest,
    OrchestratorReport,
    PrereqRedriveOutcome,
    RedriveOutcome,
    RunRecord,
    orchestrate,
    reconcile_live_runs,
    redrive_exhausted_retries,
    redrive_missing_prerequisites,
    redrive_parked_landings,
    sweep_expired_leases,
    sync_work_source,
)
from flywheel_orchestrator._strategy import (
    LANDABLE,
    LandabilityProbe,
    LandabilityVerdict,
    SandboxHandle,
    SandboxProvider,
    SandboxRequest,
    SubmitRequest,
    SubmitStrategy,
    Submitter,
    probe_landability,
)

if TYPE_CHECKING:
    from flywheel_orchestrator._claims_postgres import (
        PostgresClaimStore as PostgresClaimStore,
    )


from flywheel_orchestrator._held_out_gate import (
    FilesystemHeldOutGraderSource,
    GateOutcome,
    GateVerdict,
    HeldOutGraderError,
    HeldOutGraderSource,
    build_oracle_registration,
    evaluate_held_out_gate,
    write_oracle_registration,
    write_standing_oracle_registration,
)
from flywheel_orchestrator._github import GhRunner, GithubWorkSource
from flywheel_orchestrator._github_ci import GithubCiWorkSource
from flywheel_orchestrator._github_review import GithubReviewWorkSource
from flywheel_orchestrator._policy import (
    DEFAULT_POLICY_FILENAME,
    DEFAULT_WORKER_CONCURRENCY,
    PolicyError,
    WorkPolicy,
    build_github_ci_source,
    build_github_review_source,
    build_work_source,
    load_policy,
    resolve_grader_env,
)
from flywheel_orchestrator._sources import (
    DirectoryWorkSource,
    GraderReceipt,
    WorkItem,
    WorkReport,
    WorkSource,
    WorkSourceError,
    iter_active_phase_dirs,
    iter_active_task_files,
    load_active_tasks,
)
from flywheel_orchestrator._work_graph import (
    ExcludedTask,
    GraphValidationIssue,
    GraphValidationResult,
    WorkGraph,
    WorkGraphBuilder,
)
from flywheel_orchestrator._history import (
    TERMINAL_STATUSES,
    AttemptSummary,
    HistoryRow,
    HistoryRun,
    RunDetail,
    build_task_phase_index,
    collect_history_rows,
    collect_run_detail,
    phase_from_source,
    resolve_run_id,
)
from flywheel_orchestrator._store_factory import (
    PG_DSN_ENV,
    PG_DSN_FALLBACK_ENV,
    StoreConfigError,
    build_store,
    open_sqlite_bound_store,
    resolve_postgres_dsn,
)
from flywheel_orchestrator._workflow import (
    DEFAULT_TASKS_DIR,
    INIT_ROOT,
    LOOP_BASE_FILENAME,
    LOOP_BASE_REF_PREFIX,
    LOOP_PATH_OPTOUT_FILENAME,
    LiveRunRow,
    LoopPathOptOut,
    LoopPathOptOutError,
    TaskState,
    TaskStatusRow,
    archive_completed_phases,
    build_status_rows,
    collect_live_rows,
    load_effective_policy,
    load_loop_path_optout,
    loop_base_ref,
    phase_diff_vs_base,
    read_phase_base,
    resolve_db_path,
    select_next_task,
    status_rows_for_items,
    task_state,
    write_phase_base_if_missing,
)


def __getattr__(name: str) -> object:
    """Lazy re-export so the ``postgres`` extra stays optional."""
    if name == "PostgresClaimStore":
        from flywheel_orchestrator._claims_postgres import PostgresClaimStore

        return PostgresClaimStore
    raise AttributeError(
        f"module 'flywheel_orchestrator' has no attribute {name!r}"
    )


__all__ = [
    "AUTOPILOT_PHASE",
    "DEFAULT_AUTHORING_MAX_TURNS",
    "DEFAULT_DISCOVERY_MAX_TURNS",
    "DEFAULT_LANDING",
    "DEFAULT_TARGET_DEPTH",
    "DEFAULT_WEIGHTS",
    "GRADER_SOURCE_HELD_OUT",
    "GRADER_SOURCE_REPO_COMMAND",
    "INTERRUPT_BASE",
    "PREEMPTIVE_MAX_TIER",
    "TIER_DESCRIPTIONS",
    "TIER_WEIGHTS",
    "AuthoringResult",
    "AutopilotInvoker",
    "AutopilotPassResult",
    "DiscoveryCollection",
    "DiscoverySessionRunner",
    "DroppedFinding",
    "EmittedTask",
    "Finding",
    "ScoreBreakdown",
    "ScoredFinding",
    "ScoreWeights",
    "Tier",
    "TierVerdict",
    "author_finding",
    "author_findings",
    "authoring_prompt",
    "build_repo_invoker",
    "build_single_session_options",
    "build_single_session_runner",
    "build_tier_agents",
    "collect_tier_verdicts",
    "discover_tier",
    "emit_emitted_task",
    "orchestrator_prompt",
    "parse_tier_verdict",
    "recompute_final",
    "run_discovery",
    "run_refill_pass",
    "run_single_session_discovery",
    "score_finding",
    "select_findings",
    "sequence_findings",
    "tier_agent_key",
    "tier_prompt",
    "AttemptSummary",
    "EVENT_ACQUIRED",
    "EVENT_EXPIRED",
    "EVENT_RELEASED",
    "EVENT_RENEWED",
    "EVENT_STOLEN",
    "HUMAN_REVIEW_QUEUE_REASONS",
    "ORCHESTRATOR_EVENT_TYPES",
    "ORCHESTRATOR_STOP_EVENT_KINDS",
    "REASON_ABORTED",
    "REASON_AWAITING_APPROVAL",
    "REASON_BUDGET_CEILING",
    "REASON_NO_PROGRESS",
    "REASON_PREREQUISITE_MISSING",
    "REASON_RETRIES_EXHAUSTED_AFTER_ESCALATION",
    "ClaimLostError",
    "ClaimStore",
    "HumanReviewQueueEntry",
    "OrchestratorEventRecord",
    "OrchestratorStopEventRecord",
    "HistoryRow",
    "HistoryRun",
    "RunDetail",
    "TERMINAL_STATUSES",
    "DEFAULT_ESCALATION_BOUND",
    "DEFAULT_LANDING_REDRIVE_BOUND",
    "DEFAULT_LEASE_SECONDS",
    "DEFAULT_PREREQ_REDRIVE_BOUND",
    "DEFAULT_RECONCILE_SECONDS",
    "DEFAULT_SWEEP_SECONDS",
    "DEFAULT_POLICY_FILENAME",
    "DEFAULT_WORKER_CONCURRENCY",
    "DirectoryWorkSource",
    "EscalationDriver",
    "EscalationOutcome",
    "EscalationRequest",
    "FilesystemHeldOutGraderSource",
    "GateOutcome",
    "GateVerdict",
    "GhRunner",
    "GithubCiWorkSource",
    "GithubReviewWorkSource",
    "GithubWorkSource",
    "GraderReceipt",
    "HeldOutGraderError",
    "HeldOutGraderSource",
    "GraphSnapshotItem",
    "GraphSnapshotRecord",
    "GraphValidationIssue",
    "GraphValidationResult",
    "InMemoryClaimStore",
    "PolicyError",
    "PostgresClaimStore",
    "SqliteClaimStore",
    "StoreConfigError",
    "TaskClaim",
    "DEFAULT_TASKS_DIR",
    "INIT_ROOT",
    "LOOP_BASE_FILENAME",
    "LOOP_BASE_REF_PREFIX",
    "LOOP_PATH_OPTOUT_FILENAME",
    "LiveRunRow",
    "LoopPathOptOut",
    "LoopPathOptOutError",
    "LANDABLE",
    "LandabilityProbe",
    "LandabilityVerdict",
    "OrchestratorReport",
    "PG_DSN_ENV",
    "PG_DSN_FALLBACK_ENV",
    "PrereqRedriveOutcome",
    "RedriveOutcome",
    "RunRecord",
    "SandboxHandle",
    "SandboxProvider",
    "SandboxRequest",
    "SourceSyncRecord",
    "SubmitRequest",
    "SubmitStrategy",
    "Submitter",
    "TaskState",
    "TaskStatusRow",
    "ExcludedTask",
    "WorkGraph",
    "WorkGraphBuilder",
    "WorkItem",
    "WorkItemRecord",
    "WorkPolicy",
    "WorkReport",
    "WorkSource",
    "WorkSourceError",
    "archive_completed_phases",
    "build_github_ci_source",
    "build_github_review_source",
    "build_oracle_registration",
    "build_status_rows",
    "build_store",
    "build_task_phase_index",
    "build_work_source",
    "collect_history_rows",
    "collect_live_rows",
    "collect_run_detail",
    "evaluate_held_out_gate",
    "phase_from_source",
    "resolve_run_id",
    "iter_active_phase_dirs",
    "iter_active_task_files",
    "load_active_tasks",
    "load_policy",
    "load_effective_policy",
    "load_loop_path_optout",
    "loop_base_ref",
    "open_sqlite_bound_store",
    "orchestrate",
    "probe_landability",
    "phase_diff_vs_base",
    "read_phase_base",
    "reconcile_live_runs",
    "redrive_exhausted_retries",
    "redrive_missing_prerequisites",
    "redrive_parked_landings",
    "resolve_db_path",
    "resolve_grader_env",
    "resolve_postgres_dsn",
    "select_next_task",
    "status_rows_for_items",
    "sweep_expired_leases",
    "sync_work_source",
    "task_state",
    "write_oracle_registration",
    "write_phase_base_if_missing",
    "write_standing_oracle_registration",
]
